# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

# Repo Action 페이지에 나타날 이름 
name: Spring Boot & Maven CI/CD

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # 실행 환경 지정
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Task의 sequence를 명시한다.
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
